import type { Metadata } from "next";
import "./globals.css";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import ReactQueryProvider from "@/lib/reactQueryProvider";
import { notFound } from "next/navigation";
import { AuthProviders } from "@/lib/authProvider";
// import SessionMonitor from "@/components/auth/SessionMonitor";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "ar" }];
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  // Ensure that the incoming `locale` is valid
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <body>
        <NextIntlClientProvider>
          <ReactQueryProvider>
            <AuthProviders>
              {/* <SessionMonitor
                checkInterval={20000}
                refreshBuffer={45}
                debug={true}
              /> */}
              {children}
            </AuthProviders>
          </ReactQueryProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
